[package]
name = "legacy-parquet"
description = "The Legacy: Parquet table codecs (RFC-0001)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
legacy-format.workspace = true
arrow-array.workspace = true
arrow-schema.workspace = true
bytes.workspace = true
parquet.workspace = true
thiserror.workspace = true
